package com.swaggerapi.oraclehr.configuration;

public class Queries {
	public static String GETALLREGIONS = "SELECT * FROM REGIONS";
	public static String GETSINGLEREGIONS = "SELECT * FROM REGIONS WHERE REGION_ID = %d";
	
	public static String GETALLCOUNTRIES = "SELECT * FROM COUNTRIES";
	public static String GETSINGLECOUNTRY = "SELECT * FROM COUNTRIES WHERE COUNTRY_ID = %d";
	
	public static String GETALLDEPARTMENTS = "SELECT * FROM DEPARTMENTS";
	public static String GETSINGLEDEPARTMENT = "SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = %d";
	
	public static String GETALLLOCATIONS = "SELECT * FROM LOCATIONS";
	public static String GETSINGLELOCATION = "SELECT * FROM LOCATIONS WHERE LOCATION_ID = %d";
	
	public static String GETALLJOBS = "SELECT * FROM JOBS";
	public static String GETSINGLEJOBS = "SELECT * FROM JOBS WHERE JOB_ID = %d";
	
	public static String GETALLEMPLOYEES = "SELECT * FROM EMPLOYEES";
	public static String GETSINGLEEMPLOYEE = "SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = %d";
	
	public static String GETLASTREGIONROW = "SELECT REGION_ID FROM REGIONS WHERE REGION_ID=(SELECT MAX(REGION_ID) FROM REGIONS)";
	public static String INSERTREGION = "INSERT INTO REGIONS(REGION_ID, REGION_NAME) VALUES (%d, '%s')";
	public static String DELETEREGION = "DELETE FROM REGIONS WHERE REGION_ID = %d";
	public static String UPDATEREGION = "UPDATE REGIONS SET REGION_NAME = '%s' WHERE REGION_ID = %d";
}
